sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - travis_retry npm install

script:
  - npm test

notifications:
  email:
    - clevertonk5@gmail.com
  irc: "irc.freenode.org#nodejitsu"
